### ISSUE TITLE
InboundShipments:create_inbound_shipment_plan issue (TypeError: quote_from_bytes() expected bytes)

### ISSUE THREAD

**Issue by viavacavi** [python-amazon-mws/python-amazon-mws#214]
Hello,
I have been successfully using the mws package with the orders API.  I'm now trying to use the InboundShipments API and I'm running into issues.  I've been trying to narrow it down with simple code as such :+1:   
```python
inboundShipments = mws.InboundShipments(
    access_key=settings.get['az_access_key'], secret_key=settings.get['az_secret_key'],
    account_id=settings.get['az_seller_id'],auth_token=settings.get['az_auth_token']
)
address = {
    "name": settings.get['companyName'],
    "address_1":settings.get['address1'],
    "address_2": settings.get['address2'],
    "city": settings.get['city'],
    "district_or_county": settings.get['district'],
    "state_or_province": settings.get['region'],
    "postal_code": settings.get['postal'],
    "country": settings.get['country']
}
inboundShipments.set_ship_from_address(address)

items=[ {'sku': '012-34-5678', 'quantity': 50},  {'sku': '123-45-6789', 'quantity': 100} ]

inbound.create_inbound_shipment_plan(items,label_preference='SELLER_LABEL')
```
 

this yields the following error:
`
  File "/usr/local/lib/python3.8/dist-packages/mws/mws.py", line 1045, in create_inbound_shipment_plan
    return self.make_request(data, method="POST")
  File "/usr/local/lib/python3.8/dist-packages/mws/mws.py", line 229, in make_request
    request_description = calc_request_description(params)
  File "/usr/local/lib/python3.8/dist-packages/mws/mws.py", line 89, in calc_request_description
    encoded_value = quote(params[key], safe='-_.~')
  File "/usr/lib/python3.8/urllib/parse.py", line 839, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.8/urllib/parse.py", line 864, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

`

I'm on the latest 0.8.9 installed from Pip

Thanks!

**Comment by GriceTurrble** [comment]
While technically latest on PyPI is `0.8.10`, that's a moot point, as this is a known issue in code on `master` branch. We've corrected for issues like this on `develop` branch, which will eventually overwrite `master` for a `1.0` release.

For a quick fix, you will need to write your quantities as strings (`{'quantity': '100'}`, for example).

Seems fair to backport our cleaning logic from `develop` into here and cut a new patch release to cover it, though. Thank you!

**Comment by viavacavi** [comment]
Thank you for the reply.

Yes, I've tried passing quantities as strings:
```python
items=[ {'sku': '012-34-5678', 'quantity': '50'},  {'sku': '123-45-6789', 'quantity': '100'} ]
```

I still get the same error, however.

**Comment by viavacavi** [comment]
Update:  I just tried this with the Develop branch with no success as well (though for a different reason).  I will create a separate issue for this

**Comment by viavacavi** [comment]
Just updating this to be more clear.  On the 0.8.x branch, this does not appear to work, even when the quantities are passed as strings

**Comment by GriceTurrble** [comment]
This may be something in your `settings`, then. Is `settings['postal']` an int?

I've still got to get that cleaning code in there to sort this out properly without these edge cases. 😓

**Comment by viavacavi** [comment]
@GriceTurrble 
I don't currently have v 0.8.x installed, but I do believe that you are correct - the postal code was being returned as an Int, so I'm sure that is the problem.  Thanks!
